### ISSUE TITLE
Question: How to search by any range key

### ISSUE THREAD

**Issue by ghost** [rcambien/riverline-dynamodb#12]
Sorry for adding this as an issue but i did not found anywhere else how to ask you something.

Do you know how to create a query with a fixed Key value and Any Range Value?
I'm triying to find this in dynamodb, but i have found only that the query or scan is possible.

Thanks.
Claudio

**Comment by rcambien** [comment]
Hello,

If you don't add any range condition to a query request, you'll receive all the item with the same Hash key.

Hope it helps.
