### ISSUE TITLE
Support for batch get item?

### ISSUE THREAD

**Issue by taylorotwell** [rcambien/riverline-dynamodb#4]
Does the library currently support the "batch get item" functionality of DynamoDB?

http://docs.amazonwebservices.com/amazondynamodb/latest/developerguide/API_BatchGetItems.html

**Comment by rcambien** [comment]
Not yet but it's on the top of my Todo list.

**Comment by xanagi** [comment]
+1

**Comment by rcambien** [comment]
I start working on this feature.
It's still "work in progress" but my last commit on master works.

https://github.com/rcambien/riverline-dynamodb/blob/master/tests/Riverline/DynamoDB/ConnectionTest.php#L213

Do you have any remarks on my implementation ?

**Comment by rcambien** [comment]
Reopen this issue if you want to provide any feedbacks.

Thanks.
