### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by ghost** [rcambien/riverline-dynamodb#9]
hi,

I am new to PHP and using your work on my project, everything are perfect and thank you!

However there is only one thing I cannot figure out, that the way to handle errors. How to figure out if it is successful or not each time we get, put, scan or query?

For example of my code:

```
$new_user = new \Riverline\DynamoDB\Item('user');
$new_user['username'] = $number_id;
$new_user['password'] = '1234';
    $go = $conn->put($new_user);
```

$go is always null whatever it's success or failed, and there is no way to know if user has been created correctly.

I want to about this. Sorry for my poor English, I don't speak English very good.

Looking forward from you.

Steve

**Comment by rcambien** [comment]
Hi,

The lib throw ServerException on failure. You just need to wrap the "put" call in a try/catch to handle errors.

``` php
<?php
$new_user = new \Riverline\DynamoDB\Item('user');
$new_user['username'] = $number_id;
$new_user['password'] = '1234';

try {
    $go = $conn->put($new_user);
} catch (Riverline\DynamoDB\Exception\ServerException $e) {
    // do something
}

```
